### ISSUE TITLE
self.load .tt extension documentation in README

### ISSUE THREAD

**Issue by nikkypx** [cjheath/treetop#12]
I was just following along in the README and it might be worth adding if you use the .tt extension for your grammar file than you must specify .tt in Treetop.load 'my_grammar.tt' because it defaults to a .treetop extension

**Comment by MadBomber** [comment]
https://github.com/cjheath/treetop/blob/master/lib/treetop/polyglot.rb

**Comment by cjheath** [comment]
Processed the PR.
