### ISSUE TITLE
Small fix to the Documentation

### ISSUE THREAD

**Issue by spundun** [cjheath/treetop#20]
I created a gist, which in hindsight was an overkill. https://gist.github.com/spundun/8d43cad2b04f7a96246e

The fix is for the page http://cjheath.github.io/treetop/pitfalls_and_advanced_techniques.html
In the section `Matching Nested Structures With Non-Unique Delimeters`, simply change the second rule to 
```
rule em
  '*' (strong / !'*' . / '\*')+ '*'
end
```

instead of 
```
rule em
  '**' (strong / !'*' . / '\*')+ '**'    
end
```

**Comment by cjheath** [comment]
I processed this in Nov 2014 but didn't close the PR.
