### ISSUE TITLE
Is there a generator for grammars?

### ISSUE THREAD

**Issue by djsegal** [cjheath/treetop#28]
For rails projects, it might be nice to have a rake task that generates grammars and their respective tests

**Comment by cjheath** [comment]
Grammars for what language? You can't just pluck a grammar from the air.

**Comment by djsegal** [comment]
I meant just have some boiler plate code. nothing complex. just like a file that has 
```
grammar ExampleGrammar
   ...
end
```

and some tests to enforce TDD, i.e. `spec/grammars/example_grammar_spec.rb`

**Comment by cjheath** [comment]
If you write some and it looks generally useful, I'll consider incorporating it.
