### ISSUE TITLE
Add examples in Readme

### ISSUE THREAD

**Issue by jean-francois-labbe** [cjheath/treetop#32]
Hi, 

I'm trying to use this gem I'm surprised by the difference between the readme and the example.

In : https://github.com/cjheath/treetop/blob/master/examples/lambda_calculus/arithmetic.treetop there is 
`head:additive` 

I can't find any documentation on this `head:` 
* What is it? 
* Can I use any word? 
* Why does it references additive?

Is that possible to provide a simple example of `def apply` usage?

**Comment by cjheath** [comment]
_head_ is a label. See the documentation under the heading Labels in http://cjheath.github.io/treetop/semantic_interpretation.html
