### ISSUE TITLE
Unfork repo

### ISSUE THREAD

**Issue by sandstrom** [cjheath/treetop#35]
Looks like this is the new canonical repo. If so, we should unfork it. Just send a message to Github and ask them to unfork this repo, they'll do it.

Would also be good if we could start publishing gems from here. Would need to ask @nathansobo for the keys, or if we somehow can transfer the gem name. I honestly don't know exactly how that works 😄

**Comment by cjheath** [comment]
I have been publishing the gem since 2007, and from this repository since
it was created.

Why should we unfork?

**Comment by sandstrom** [comment]
If this is the canonical repo, it makes sense to unfork. Clarity around which which is canonical will help people focus issues/contributions/PRs to the right repo.

*(if gems are already published from this repo I don't think we should change anything around that, my misunderstanding!)*

**Comment by cjheath** [comment]
What is unclear about the README.md on https://github.com/nathansobo/treetop ?
What is unclear about the homepage listed on https://rubygems.org/gems/treetop ?
I don't want to cut ties from Nathan Sobo's original work. I've only tweaked it, I didn't write it. I don't think it makes sense to unfork.
