### ISSUE TITLE
Unfork

### ISSUE THREAD

**Issue by sandstrom** [cjheath/treetop#37]
Great project! 🏅 

To make it more obvious that this is the canonical repo it would be neat if we could unfork it.

All that's needed is to send an email to Github (from this repo maintainer/owner) asking them to unfork.

**Comment by cjheath** [comment]
We had this discussion already and none of the salient factors have changed.

98% of the code is from the original repo, as handed over to me in 2008, and I want to retain that link as an ongoing credit to Nathan's original work. The first section of the README announces that this is the origin of the gem, as does the gemspec and [https://rubygems.org/gems/treetop](https://rubygems.org/gems/treetop).

If you still find that confusing, I don't know what to say. I see no reason to change this.

**Comment by sandstrom** [comment]
@cjheath Hehe, I just noticed that I've already suggested this 😄 Sorry, I didn't aim to be annoying, it's just that I usually make this suggestion to repos when I see them forked (and forgot that I'd already made this suggestion here).
