### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by voxik** [cjheath/treetop#39]
Could you please push release tags into repository? Thx.

**Comment by cjheath** [comment]
Tags are not a normal part of my workflow, so I need a reason to change. What do you use them for?

**Comment by voxik** [comment]
Having Treetop packaged in Fedora, I want to run test suite during build of the package. Because test suite is not included in the released gem, I have take it from the repository. It would be convenient to take the test suite from the same point where the release was cut off.

**Comment by cjheath** [comment]
I see, that makes sense. So Treetop 1.6.10 gem would use what tag syntax?

**Comment by voxik** [comment]
v1.6.10 or just 1.6.10. Both are understandable what they mean.

**Comment by cjheath** [comment]
Ok, I'll do that tomorrow, thanks for explaining.

**Comment by voxik** [comment]
Thx a lot!

**Comment by cjheath** [comment]
tagged v1.6.10 per your request
