### ISSUE TITLE
String#blank? is creating issues.

### ISSUE THREAD

**Issue by marcandre** [cjheath/treetop#41]
Please remove and use `empty?` or use a [better definition](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/core_ext/string.rb)

See [this for details](https://github.com/rubocop-hq/rubocop/issues/8636#issuecomment-686156607)

**Comment by cjheath** [comment]
Removed and released as 1.6.11

**Comment by marcandre** [comment]
Awesome, thanks for the quick fix 🎉
