### ISSUE TITLE
Bug parsing context-sensetive grammar

### ISSUE THREAD

**Issue by stereobooster** [cjheath/treetop#42]
I took example from Ford's original paper:

```
A ← aAb/ε
B ← bBc/ε
S ← &(A!b)a∗ B!.
```

And it seems doesn't work as expected:

```ruby
grammar ContextSensetive
  rule s
    &(a !'b') 'a'* b
  end

  rule a
    'a' a 'b' / ''
  end

  rule b
    'b' b 'c' / ''
  end
end
```

```ruby
require 'rubygems'
require 'treetop'
Treetop.load 'context_sensetive'

parser = ContextSensetiveParser.new
p !parser.parse('aabbcc').nil?  # correct: true
p !parser.parse('aabbccc').nil? # correct: false
p !parser.parse('aaabbcc').nil? # incorrect: true
```

**Comment by cjheath** [comment]
The Treetop mailing list is used for support: treetop-dev@googlegroups.com

Your implementation does not detect EOF - the original uses !.

**Comment by stereobooster** [comment]
> Your implementation does not detect EOF - the original uses !.

Yes I know. I wasn't sure how end of file denoted in Treetop

```ruby
grammar ContextSensetive
  rule s
    &(a !'b') 'a'* b !.
  end

  rule a
    'a' a 'b' / ''
  end

  rule b
    'b' b 'c' / ''
  end
end
```

this code produces the same error

**Comment by cjheath** [comment]
Your questions will be answered *only* if you ask the on the mailing list, not in a github issue. Not really sure if I can find another way to say that :)

**Comment by stereobooster** [comment]
Case closed. I found paper which shows, that this is indeed an issue in PEG. And it can't handle this grammar the way Ford described https://arxiv.org/pdf/1801.10490.pdf
