### ISSUE TITLE
What's the general technique to achieve non-greedyness?

### ISSUE THREAD

**Issue by sergueif** [cjheath/treetop#46]
Hello, I often find myself wanting to write a rule like
```
rule document
  junk stuff_i_care_about junk
end

rule junk
  .*
end

rule stuff_i_care_about
  '## ' .* newline_or_end_of_file
end
```

But then junk greedily consumes everything. I also often run into trouble with "newline or end of file" type of rule, but maybe that's a separate issue.

that's the general way of replicating the semantics of regex non-greedy-star pattern? (`.*?`)

**Comment by cjheath** [comment]
In general you repeat a "match more if it's not too much" pattern, using a negative lookahead.
E.g.
```
rule stuff_i_care_about
  '## ' ( !newline_or_end_of_file . )* newline_or_end_of_file
end
```

**Comment by cjheath** [comment]
Also, matching end of file requires negative lookahead too ("NOT anything"):
```
rule end_of_file
  ! .
end
```

**Comment by sergueif** [comment]
hmmm, I'll give both of these a try. The `end_of_file` negative match I tried before, but kept running into infinite loop when looking for repeating patterns of junk (empty lines, lines that are just whitespace, optional lines, etc.)

It would be good for the website or examples folder to include an example to illustrate parsing something like a code/programming language file to show off how to deal with all the ignored white space

e.g. `hello_world.rb` (Ruby)
```
# comment
# comment 2
puts "hello world"

```

Something to illustrate the table-stakes that there can be any number of comment lines, there can be whitespace tabs spaces before and after anything else but it's "not interesting"

**Comment by cjheath** [comment]
Have you seen https://cjheath.github.io/treetop/syntactic_recognition.html ?
