### ISSUE TITLE
Wrong website link in the repo properties

### ISSUE THREAD

**Issue by hwood-vivup** [cjheath/treetop#50]
This repo "about" properties lists this URL:
https://cjheath.github.com/treetop

Looks like it should be...
https://cjheath.github.io/treetop/

**Comment by cjheath** [comment]
Where do you see this problem please? I can't see the incorrect URL anywhere in the repository.

**Comment by hwood-vivup** [comment]
@cjheath Yeah it's not in the code anywhere. It's in the github settings for the repository, so the link shows in github in the top right panel

**Comment by cjheath** [comment]
Ahh, right you are. I'll fix it when I'm back at a computer again. Thanks.

**Comment by cjheath** [comment]
Done, thanks again.
