### ISSUE TITLE
Can't namespace parser using classes

### ISSUE THREAD

**Issue by Wardrop** [cjheath/treetop#8]
Some of us have the request to use classes in our namespaces. Treetop doesn't currently allow you to do this, e.g.

``` ruby
class SomeClass
  grammer Accept
    
  end
end
```

It would be appreciated if this could be added. In the mean time I'm defining my grammars outside of any class or module, and using the following line of code to line my parsers into the namespace I desire, instead of `Treetop.load`:

``` ruby
class_eval Treetop::Compiler::GrammarCompiler.new.ruby_source_from_string(File.read('accept.treetop'))
```

Cheers

**Comment by cjheath** [comment]
Fixed and pushed to github, and as gem version 1.6.8
